#!/bin/sh

PREREQ=""


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions
echo "I: add '$0'"


dumpkeys < /dev/tty1 | gzip > "$DESTDIR"/etc/boottime.kmap.gz

copy_exec /bin/loadkeys /bin/loadkeys
copy_exec /usr/bin/kbd_mode /bin/kbd_mode

