#!/bin/sh

PREREQ="busybox"

APPLET_BLACKLIST=
APPLET_BLACKLIST="$APPLET_BLACKLIST hostid"
#APPLET_BLACKLIST="$APPLET_BLACKLIST depmod modprobe"
#APPLET_BLACKLIST="$APPLET_BLACKLIST ip ifconfig"

prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = "prereqs" ] && prereqs
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_ADD_BUSYBOX_APPLETS" in
  0 | no | n ) exit 0;;
esac

echo "I: add '$0'"

set -e
for app in $(/bin/busybox | awk 'BEGIN {p=0} /functions:$/ {p=1} /,/ { gsub(",", ""); if (p == 1) print $0 }'); do

  case "$APPLET_BLACKLIST" in
		"$app" ) continue ;;
		*" $app" ) continue ;;
		"$app"* ) continue ;;
		*" $app "* ) continue ;;
	esac
	[ -x "$DESTDIR/bin/$app" ] && continue
  [ -x "$DESTDIR/sbin/$app" ] && continue

  ln -sf busybox "$DESTDIR/bin/$app"
done

