#!/bin/bash

PREREQ="busybox add-busybox-applets"

CMDS=
CMDS="$CMDS openvt chvt deallocvt fgconsole"
CMDS="$CMDS mountpoint"
CMDS="$CMDS strace ltrace ldd"
CMDS="$CMDS flashrom"
CMDS="$CMDS gdisk cfdisk fdisk"
CMDS="$CMDS e2fsck tune2fs"
CMDS="$CMDS btrfs"
CMDS="$CMDS gpm"
CMDS="$CMDS tcpdump"
CMDS="$CMDS mii-tool ethtool rfkill"
CMDS="$CMDS ps pkill pgrep"
CMDS="$CMDS iostat"
CMDS="$CMDS htop"
CMDS="$CMDS ddrescue"
CMDS="$CMDS ip vconfig brctl ifconfig"
CMDS="$CMDS run-parts"
CMDS="$CMDS tty reset stty"
CMDS="$CMDS minicom rz sz rx sx"
CMDS="$CMDS keyctl"


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = "prereqs" ] && prereqs
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_ADD_DEBUG_HELPERS" in
  0 | no | n ) exit 0;;
esac



echo "I: add '$0'"


PATH=/sbin:/bin:/usr/sbin:/usr/bin
for cmd in $CMDS; do
  if file="$(which "$cmd")"; then
    rm -f "$DESTDIR/bin/$cmd"
    copy_exec "$file" "/bin"
  else
    echo "$0: warning $cmd not avail, thus not installed" >&2
  fi
done

VT=13
LOCAL_SCRIPT="vt$VT"

mkdir -p "$DESTDIR/var" "$DESTDIR/usr/sbin" "$DESTDIR/usr/bin"
ln -s /run "$DESTDIR/var/run"
ln -s ../../bin/gpm "$DESTDIR/usr/sbin"/gpm

cat > "$DESTDIR"/bin/rcgpm << EOF
#!/bin/sh
set -x
kill \$(cat /run/gpm.pid 2> /dev/null) 2> /dev/null
/usr/sbin/gpm -m /dev/input/mice -t imps2
EOF
chmod 755 "$DESTDIR"/bin/rcgpm

for d in /etc/terminfo /lib/terminfo /usr/share/terminfo; do
  mkdir -p "$DESTDIR/${d%/*}"
  cp -a "$d" "$DESTDIR/${d%/*}"
done

mkdir -p "$DESTDIR/scripts/init-bottom"
cat > "$DESTDIR/scripts/init-bottom/$LOCAL_SCRIPT" << EOF
#!/bin/sh
[ "\$1" = prereqs ] && exit 0

kill \$(cat /run/$LOCAL_SCRIPT.pid 2> /dev/null) 2> /dev/null || :
kill \$(cat /run/gpm.pid 2> /dev/null) 2> /dev/null || :
kill \$(ls -l /proc/[1-9]*/fd/[0-9]* 2> /dev/null | sed -n '/\/dev\/tty'$VT'$/ s@^.*/proc/\([0-9]\+\).*$@\1@ p') 2> /dev/null

[ -x /bin/deallocvt ] && /bin/deallocvt
[ -x /bin/chvt ] && /bin/chvt 1

exit 0
EOF

mkdir -p "$DESTDIR/scripts/init-top"
cat > "$DESTDIR/scripts/init-top/$LOCAL_SCRIPT" << EOF
#!/bin/sh
PREREQ="udev keymap"

prereqs() { echo "\$PREREQ"; exit 0; }
[ "\$1" = prereqs ] && prereqs

if [ "\$1" = getty ]; then
  echo \$$ > /run/$LOCAL_SCRIPT.pid
  clear="\$(clear)"
  echo -n "\$clear"
  while [ -x /bin/busybox ]; do
    stty -echo
    echo -n "\${clear}Press a key."
    read foo
    stty echo
    [ -x /bin/sh ] && \
      PATH=/sbin:/bin:/usr/sbin:/usr/bin \
      PS1='\w\$ ' \
        /bin/sh -l
  done
  echo -n "\$clear"
  exit 0
fi

[ -x /bin/openvt ] && /bin/openvt -c $VT "/scripts/init-top/$LOCAL_SCRIPT" getty || :
[ -x /bin/rcgpm ] && /bin/rcgpm || :

exit 0
EOF
chmod 755 "$DESTDIR/scripts/init-top/$LOCAL_SCRIPT" "$DESTDIR/scripts/init-bottom/$LOCAL_SCRIPT"
cp -a "$DESTDIR/scripts/init-bottom/$LOCAL_SCRIPT" "$DESTDIR/scripts/local-bottom/$LOCAL_SCRIPT"

cat > "$DESTDIR"/etc/profile << EOF
PATH=/sbin:/bin:/usr/sbin:/usr/bin
PS1='(initramfs) \w\$ '
[ -x /bin/ps ] && alias ps=/bin/ps
EOF

