#!/bin/sh

PREREQ=""

prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_ADD_LOADED_KEYMAP" in
  0 | no  | n ) exit 0;;
esac


echo "I: add '$0'"

[ -x "/usr/share/initramfs-tools/hooks/keymap" ] && ( KEYMAP=y . /usr/share/initramfs-tools/hooks/keymap; )

dumpkeys < /dev/tty1 | gzip > "$DESTDIR"/etc/boottime.kmap.gz

copy_exec /bin/loadkeys /bin/loadkeys

if ! copy_exec /usr/bin/kbd_mode /bin/kbd_mode; then
  copy_exec /bin/kbd_mode /bin/kbd_mode
fi

