#!/bin/sh

PREREQ="busybox dropbear"


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_FIX_CRYPTROOT_DROPBEAR" in
  1 | yes | y ) :;;
  * ) exit 0;;
esac

echo "I: add '$0'"


[ -z "$DESTDIR" ] && exit 1

# ensure all libnss stuff is there
ls /lib/*/libns[ls]*.so* | sed 's@/[^/]\+$@@g' | sort -u | while read dir; do
  mkdir -p "$DESTDIR"/$dir
  cp "$dir"/libns[ls]*.so* "$DESTDIR"/$dir
done

# don't use /root as ssh-key are left behind after switch_root, just a minor space loss
rm -rf "$DESTDIR"/root/.ssh

: > "$DESTDIR"/etc/shells
echo /bin/sh >> "$DESTDIR"/etc/shells
echo /bin/CRYPT >> "$DESTDIR"/etc/shells

mkdir -p "$DESTDIR"/.ssh
chmod 600 "$DESTDIR"/.ssh
: > "$DESTDIR"/etc/passwd
while IFS=: read user foo uid foo foo home foo; do
  [ $uid -lt 1000 -a $uid -ne 0 ] && continue
  [ -f "$home/.ssh/authorized_keys" ] || continue
  desthome="$home"
  shell=/bin/CRYPT
  [ $uid -eq 0 ] && desthome=/
  [ $uid -eq 0 ] && shell=/bin/sh
  mkdir -p "$DESTDIR/$desthome"/.ssh
  cat "$home"/.ssh/authorized_keys > "$DESTDIR/$desthome"/.ssh/authorized_keys
  chmod 600 "$DESTDIR/$desthome"/.ssh/authorized_keys
  echo "$user:x:0:0:$user:$desthome:$shell" >> "$DESTDIR"/etc/passwd
  [ $uid -eq 0 ] && echo "unlock:x:0:0:root:/:/bin/CRYPT" >> "$DESTDIR"/etc/passwd
done < /etc/passwd

# if dropbear is active use real hostkey from dropbear
if pidof -s dropbear > /dev/null; then
  for i in dss rsa ecdsa; do 
    if [ -f /etc/dropbear/dropbear_${i}_host_key ]; then
      cat /etc/dropbear/dropbear_${i}_host_key > "$DESTDIR"/etc/dropbear/dropbear_${i}_host_key
      chmod 600 "$DESTDIR"/etc/dropbear/dropbear_${i}_host_key
    fi
  done
elif pidof -s sshd > /dev/null; then 
  for type in rsa dsa:dss ecdsa; do
    openssh_type="${type%:*}"
    dropbear_type="${type#*:}"
    if ! /usr/lib/dropbear/dropbearconvert openssh dropbear /etc/ssh/ssh_host_${openssh_type}_key "$DESTDIR"/etc/dropbear/dropbear_${dropbear_type}_host_key 1> /dev/null 2>&1; then
      echo "W: converting /etc/ssh/ssh_host_${dropbear_type}_key failed" >&2
    fi
    chmod 600 "$DESTDIR"/etc/dropbear/dropbear_${dropbear_type}_host_key
    if ! cmp /etc/dropbear/dropbear_${dropbear_type}_host_key "$DESTDIR"/etc/dropbear/dropbear_${dropbear_type}_host_key 2> /dev/null 1>&2; then
      echo "W: system's dropbear and openssh $openssh_type keys differ" >&2
      if [ "$X_FIX_CRYPTROOT_SYNC_KEYS" = y ]; then
        echo "I: sync openssh $openssh_type key to system dropbear host key" >&2
        cat "$DESTDIR"/etc/dropbear/dropbear_${dropbear_type}_host_key > /etc/dropbear/dropbear_${dropbear_type}_host_key
        chmod 600 /etc/dropbear/dropbear_${dropbear_type}_host_key
      fi
    fi 
  done
fi

cat > "$DESTDIR"/bin/CRYPT << 'EOF'
#!/bin/sh

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

/scripts/local-top/cryptroot
case "$1" in
  skip | -f ) : ;;
  * )
    pkill -9 ^askpass
    pkill dropbear
    ;;
esac

EOF
chmod 755 "$DESTDIR"/bin/CRYPT

copy_exec /usr/bin/pgrep /bin/pgrep
copy_exec /usr/bin/pkill /bin/pkill

copy_exec /usr/bin/scp

