#!/bin/sh

# LICENSE:   GPL, see LICENSE file
# Author(s): Joerg Jungermann

PREREQ=""


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_FORCE_NETWORK_UNLOAD_MODULES" in
  1 | yes | y ) :;;
  * ) exit 0;;
esac



echo "I: add '$0'"


LOCAL_SCRIPT="${0##*/}"

mkdir -p "$DESTDIR/scripts/local-bottom"
cat > "$DESTDIR/scripts/local-bottom/$LOCAL_SCRIPT" << EOF
#!/bin/sh
PREREQ="ifdown-all"
if [ "\$1" = prereqs ]; then
  echo "\$PREREQ"
  exit 0
fi

for i in /sys/class/net/*/device/driver; do
  [ -d "\$i" ] || continue
  m="\$(readlink -f \$i)"
  m="\${m##*/}"
  rmmod \$m 2> /dev/null
done

/sbin/brctl show | busybox tail -n +2 | while read br _tmp; do
  ifconfig \$br down
  /sbin/brctl delbr \$br
done

[ -f /run/network/ifstate ] && rm -f /run/network/ifstate

exit 0
EOF
chmod 755 "$DESTDIR/scripts/local-bottom/$LOCAL_SCRIPT"

