#!/bin/sh

PREREQ=""


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions
echo "I: add '$0'"


mkdir -p "$DESTDIR"/etc "$DESTDIR"/conf/conf.d

set -e
if [ -f "$DESTDIR"/conf/conf.d/cryptroot ]; then
  grep resume "$DESTDIR"/conf/conf.d/cryptroot > "$DESTDIR"/conf/conf.d/cryptroot.new
  grep -v resume "$DESTDIR"/conf/conf.d/cryptroot >> "$DESTDIR"/conf/conf.d/cryptroot.new
fi

if [ -f /etc/crypttab ]; then
  while read name dev key type comment attrib; do
    case "$name" in
      \#* ) continue ;;
    esac

    [ "$type" = luks ] || continue
    echo "target=$name,source=$dev,key=$key,rootdev"
  done < /etc/crypttab >> "$DESTDIR"/conf/conf.d/cryptroot.new
fi

mv -f "$DESTDIR"/conf/conf.d/cryptroot.new "$DESTDIR"/conf/conf.d/cryptroot
