#!/bin/sh

# force cryptroot if somehow initrd does not detect, that cryptroot is needed
# - this forces include of cryptroot hook
# - if we have an resume partition, it will be unlocked at first


PREREQ="cryptroot"

prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
if ! [ -f /usr/share/initramfs-tools/hooks/cryptroot ]; then
  echo "W: /usr/share/initramfs-tools/hooks/cryptroot does not exist."
fi
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_FORCE_CRYPTROOT" in
  1 | yes | y ) :;;
  * ) exit 0;;
esac



echo "I: add '$0'"

(
  CRYPTSETUP=y
  . /usr/share/initramfs-tools/hooks/cryptroot
)

mkdir -p "$DESTDIR"/etc "$DESTDIR"/conf/conf.d

if [ -f "$DESTDIR"/conf/conf.d/cryptroot ]; then
  grep resume "$DESTDIR"/conf/conf.d/cryptroot > "$DESTDIR"/conf/conf.d/cryptroot.new
  grep -v resume "$DESTDIR"/conf/conf.d/cryptroot >> "$DESTDIR"/conf/conf.d/cryptroot.new
fi

set -e
if [ -f /etc/crypttab ]; then
  while read name dev key type comment attrib; do
    case "$name" in
      \#* ) continue ;;
    esac

    [ "$type" = luks ] || continue
    echo "target=$name,source=$dev,key=$key,rootdev" >> "$DESTDIR"/conf/conf.d/cryptroot.new
  done < /etc/crypttab
fi
mv -f "$DESTDIR"/conf/conf.d/cryptroot.new "$DESTDIR"/conf/conf.d/cryptroot

