#!/bin/sh

PREREQ=""

prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions
echo "I: add '$0'"


mkdir -p "$DESTDIR"/etc/udev/rules.d

cat > "$DESTDIR"/etc/udev/rules.d/99-force-resume-on-device-add.rules << EOF

# force instant resume try on disk appearence
ACTION=="add", PROGRAM+="/bin/FORCE-resume"

EOF

cat > "$DESTDIR/bin/FORCE-resume" << EOF
#!/bin/sh
exec >> /FORCE-resume.log 2>&1
echo
echo "### $(/bin/busybox date)"
env
(
  for x in \$(cat /proc/cmdline); do
    case "\$x" in
      resume=* )
        export resume="\${x#*=}"
        ;;
      noresume )
        export noresume=yes
        ;;
    esac
  done
  [ "\$noresume" = yes ] && exit 0

  vgchange -ay
  for i in 1 2 3 4 5; do
    sh /scripts/local-premount/resume
    sleep 1
  done
) &
EOF
chmod 755 "$DESTDIR/bin/FORCE-resume"

