#!/bin/sh

# LICENSE:   GPL, see LICENSE file
# Author(s): Joerg Jungermann

PREREQ=""


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_STRIP_KMODS" in
  1 | yes | y ) :;;
  * ) exit 0;;
esac

echo "I: add '$0'"

find "$DESTDIR"/lib/modules/ -name "*.ko" -exec strip --strip-debug {} +

