#!/bin/sh

PREREQ="busybox add-busybox-applets"


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_SUBST_IPCONFIG_UDHCP_ETH0" in
  1 | yes | y ) :;;
  * ) exit 0;;
esac


echo "I: add '$0'"


rm -f "$DESTDIR"/bin/ipconfig

mkdir -p "$DESTDIR"/etc/udhcpc/
cp -a /etc/udhcpc/default.script "$DESTDIR"/etc/udhcpc/default.script
chmod 755 "$DESTDIR"/etc/udhcpc/default.script

cat > "$DESTDIR"/bin/ipconfig << EOF
#!/bin/sh

if ! [ -f /ipconfig.lock ]; then
  exec 3> /ipconfig.lock
  trap 'rm -f /ipconfig.lock; exit 0;' EXIT QUIT INT KILL TERM HUP USR1 USR2
  if ! ip link show dev eth0 | grep ,UP > /dev/null; then
    if ! /bin/busybox udhcpc -i eth0 -t 5 -T 5 -n -q; then
      while [ -x /bin/busybox ]; do
        for i in /sys/class/net/*; do
          if="\${i##*/}"
          [ -f "\$i/type" ] || continue
          [ "\$(cat "\$i/type")" = 1 ] || continue
          ip link show dev \$if | grep ,UP > /dev/null && continue
          /bin/busybox udhcpc -i \$if -t 3 -T 3 -n -q
        done
        sleep 60
      done
    fi
  fi
fi
EOF
chmod 755 "$DESTDIR"/bin/ipconfig

[ -x "$DESTDIR"/sbin/ifconfig ] || ln -s ../bin/busybox "$DESTDIR"/sbin/ifconfig
[ -x "$DESTDIR"/sbin/route ] || ln -s ../bin/busybox "$DESTDIR"/sbin/route

