#!/bin/sh

# LICENSE:   GPL, see LICENSE file
# Author(s): Joerg Jungermann

PREREQ="busybox add-busybox-applets"


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_SUBST_IPCONFIG_UDHCP" in
  1 | yes | y ) :;;
  * ) exit 0;;
esac


echo "I: add '$0'"
set -e

rm -f "$DESTDIR"/bin/ipconfig

mkdir -p "$DESTDIR"/etc/udhcpc/
cp -a /etc/udhcpc/default.script "$DESTDIR"/etc/udhcpc/default.script
chmod 755 "$DESTDIR"/etc/udhcpc/default.script

cp -a /etc/hostname "$DESTDIR"/etc/hostname

cat > "$DESTDIR"/bin/ipconfig << EOF
#!/bin/sh

if ! [ -f /ipconfig.lock ]; then
  exec 3> /ipconfig.lock

  hostname="\$(cat /etc/hostname)"

  trap 'rm -f /ipconfig.lock; exit 0;' EXIT QUIT INT KILL TERM HUP USR1 USR2
  for i in /sys/class/net/*; do
    while [ -x /bin/busybox ]; do # detect if we pivot_rooted
      ls /run/net-*.conf 1> /dev/null 2>&1 && break
      if="\${i##*/}"
      [ -f "\$i/type" ] || break
      [ "\$(cat "\$i/type")" = 1 ] || break
      if /bin/busybox udhcpc -i \$if -t 3 -T 3 -n -q -x hostname:\$hostname 2> /dev/null 1>/dev/null; then
        echo "# \$if configured"              > /run/net-\$if.conf
        ip a show dev \$if | sed 's/^/#   /' >> /run/net-\$if.conf
        cat /run/net-\$if.conf
        break
      fi
      ip addr flush \$if
      ip link set down \$if
      sleep 1
    done &
  done
  wait
fi
EOF
chmod 755 "$DESTDIR"/bin/ipconfig

[ -x "$DESTDIR"/sbin/ifconfig ] || ln -sf ../bin/busybox "$DESTDIR"/sbin/ifconfig
[ -x "$DESTDIR"/sbin/route ] || ln -sf ../bin/busybox "$DESTDIR"/sbin/route

