#!/bin/sh

PREREQ="udev"


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_ADD_UDEV_RULES" in
  1 | yes | y ) :;;
  * ) exit 0;;
esac



echo "I: add '$0'"


mkdir -p "$DESTDIR"/etc/udev/rules.d
cp -a /etc/udev/rules.d "$DESTDIR"/etc/udev/

