#!/bin/sh -e

# LICENSE:   GPL, see LICENSE file
# Author(s): Joerg Jungermann

PREREQ="udev"


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions

[ -f /etc/initramfs-tools/conf.d/initramfs-x.conf ] && . /etc/initramfs-tools/conf.d/initramfs-x.conf
case "$X_UDEV_PERSISTENT_NET_RULES" in
  1 | yes | y ) :;;
  * ) exit 0;;
esac

echo "I: add '$0'"


if [ -e /etc/udev/rules.d/70-persistent-net.rules ]; then
  cp -p /etc/udev/rules.d/70-persistent-net.rules $DESTDIR/lib/udev/rules.d/
fi
