#!/bin/sh

PREREQ="udev"


prereqs() { echo "$PREREQ"; exit 0; }
[ "$1" = prereqs ] && prereqs
. /usr/share/initramfs-tools/hook-functions
echo "I: add '$0'"


mkdir -p "$DESTDIR"/etc/udev/rules.d
cp -a /etc/udev/rules.d "$DESTDIR"/etc/udev/

